# Generated by Django 4.1.3 on 2023-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_date', models.DateField()),
                ('Region', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=255)),
                ('Product', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
            ],
            options={
                'db_table': 'prod',
            },
        ),
    ]
